name: Publish Expo Native Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.1). Do NOT include "v" prefix.'
        required: true
        type: string
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Build and Publish Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update package.json version (Manual Trigger Only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Updating package.json to version ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --no-git-tag-version --allow-same-version

      - name: Check npm user authentication for GHP
        run: npm whoami --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Expo Native Module
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up Node.js for Public NPM Registry
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://registry.npmjs.org/'
      #     cache: 'npm'

      # - name: Publish to Public NPM Registry
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
